<?php
$routes=[
    "/"=>"page@home",
    "/about-us"=>"page@about",
    "/services"=>"page@services",
    "/courses"=>"courses@index",
    "/course-delete"=>"courses@delete",
    "/batch"=>"batch@index",
    "/batch-delete"=>"batch@delete",
    "/api-courses"=>"api@courses",
    "/api-batches"=>"api@batches"
];